### ISSUE TITLE
Fresh nix install yields elm version mismatch

### ISSUE THREAD

**Issue by gmilleramilar** [elm-in-elm/compiler#127]
I created a fresh Nix installation, and attempted to build the project, getting an elm version mismatch error. Am I missing something?

```
[nix-shell:~/dev/compiler]$ make
rm -rf build/elm.js elm-stuff
cd cli && npx elm make Main.elm --output ../build/elm.js
-- ELM VERSION MISMATCH ----------------------------------------------- elm.json

Your elm.json says this application needs a different version of Elm.

It requires 0.19.1, but you are using 0.19.0 right now.

make: *** [Makefile:26: build] Error 1

[nix-shell:~/dev/compiler]$

```

**Comment by Janiczek** [comment]
Hello!

I believe our `shell.nix` is just using an old snapshot of nixpkgs (back then nixpkgs-channels).

One way to go might be to find a newer snapshot (particularly the `sha256` field for the newest `rev` of nixpkgs we can find) with `nix-prefetch-url --unpack <URL>` ([it seems](https://github.com/NixOS/nix/issues/1880#issuecomment-366615204)).
I can't currently do that because I'm on a new machine and don't have Nix installed yet. Perhaps you can?

Other way might be to not use a snapshot at all?
Something like [here](https://github.com/aforemny/elm-mdc/blob/master/shell.nix) perhaps?

(I'm not all that well versed in Nix so I might be wrong 🤷 )

**Comment by Janiczek** [comment]
I've tried stuff out in a NixOS VM and updated `shell.nix` in a3a63e974964f0327099ab2be532ea5c27627857

**Comment by gmilleramilar** [comment]
Yes, it gets further now, but it broke complaining that it couldn't find package "yargs" Probably a different issue, but running "npm install yargs" appears to have fixed that.

**Comment by Janiczek** [comment]
Hmm, `yargs` are listed in dependencies in `project.json`. I believe it's alright then. The CLI for the compiler is essentially a Node application, it needs you to run `npm install` or `yarn` beforehand.
