### ISSUE TITLE
Reuse code from decgen

### ISSUE THREAD

**Issue by FranzSkuffka** [elm-in-elm/compiler#26]
This module here parses pretty much all types already. Why not re-use the code?

https://github.com/dkodaj/decgen

**Comment by Janiczek** [comment]
@FranzSkuffka Thanks for the link!

Seems the project uses String.split and Regex instead of parsers. I think we're pretty invested in elm/parser at this point.

Also maybe I just don't get what we should reuse from here. Can you elaborate a bit more, and/or point to specific files / regions?

**Comment by FranzSkuffka** [comment]
I just think that reusing code would allow this project to make a big step regardless of the parsing technique used. I also do not think it would really harm to use a different parsing technique.

What are your concerns? Unfortunately I can not point to specific files but the repo is pretty small..

**Comment by Janiczek** [comment]
Well, what I mean is - what part of the code did you mean to reuse, or use it for. Parsing custom types like
```elm
type Foo
  = Bar String
  | Baz Int Bool
  | Quux
```
? Or records? etc. (That seems to all be in the [Destructuring.elm](https://github.com/dkodaj/decgen/blob/master/src/Destructuring.elm) file)

With the goal of this repo for the code to be idiomatic, "best practices" etc. I'm not sold on mixing parsing techniques (Parser vs String/Regex), sorry :slightly_frowning_face:

**Comment by FranzSkuffka** [comment]
I see lots of red here but maybe that's outdated.
<img width="824" alt="image" src="https://user-images.githubusercontent.com/7485959/60684854-4c165a00-9ea0-11e9-9d7e-9e6f4c389b95.png">

**Comment by Janiczek** [comment]
Yeah that's current. There are a lots of red still. But again, reusing codebase that does things via String.split / Regex is most likely a no-go for me. We can draw inspiration for sure! But I won't copy-paste and adapt it.

I've had similar dilemma with [stil4m/elm-syntax](https://package.elm-lang.org/packages/stil4m/elm-syntax/latest/) which uses `elm/parser` but builds its own 0.18-parser-combinators-like abstraction (IIRC) underneath so that it can use 0.18 code. If I used it I'd have all the parsers green almost without any work! But I don't want to do it since I want this codebase to have `elm/parser` idiomatic parsers.

So I'm sorry but I'll close this issue. I hope you understand my standpoint.

**Comment by FranzSkuffka** [comment]
Okey, really respect appreciate the approach you are taking to this. Very cool project. Loved seeing you in paris.
